//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursak_Ol
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestionAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestQuestionAnswer()
        {
            this.IsAnswer = 0;
            this.UserTestAnswer = new HashSet<UserTestAnswer>();
        }
    
        public int Id { get; set; }
        public string Answer { get; set; }
        public byte IsAnswer { get; set; }
        public int TestQuestionId { get; set; }
    
        public virtual TestQuestion TestQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTestAnswer> UserTestAnswer { get; set; }
    }
}
