//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursak_Ol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tests_DBContainer : DbContext
    {
        public Tests_DBContainer()
            : base("name=Tests_DBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<TestCreator> TestCreator { get; set; }
        public virtual DbSet<TestQuestion> TestQuestion { get; set; }
        public virtual DbSet<TestQuestionAnswer> TestQuestionAnswer { get; set; }
        public virtual DbSet<UserTest> UserTest { get; set; }
        public virtual DbSet<UserTestAnswer> UserTestAnswer { get; set; }
    }
}
