//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursak_Ol
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTestAnswer
    {
        public int Id { get; set; }
        public int UserTestId { get; set; }
        public int TestQuestionId { get; set; }
        public int UserTestQuestionAnswerId { get; set; }
        public System.DateTime AnswerDate { get; set; }
    
        public virtual UserTest UserTest { get; set; }
        public virtual TestQuestion TestQuestion { get; set; }
        public virtual TestQuestionAnswer TestQuestionAnswer { get; set; }
    }
}
